### ISSUE TITLE
sidebar二级标题太长的时候发现无法展示全部内容

### ISSUE THREAD

**Issue by AZeC4** [shenweiyan/WebStack-Hugo#59]
<img width="152" alt="Image" src="https://github.com/user-attachments/assets/dc4861b1-9a3d-455e-bbe0-f56740210f41" />

你好，没有一点前端开发经验，这边使用主题的时候遇到了这种二级标题内容太长的时候会存在截断的问题，请问要如何解决呢。这边通过问cursor，自动修改了style.css但是hugo server之后，发现还是没能实现自己想要的效果，所以过来问一下，期待您的解答。

**Comment by shenweiyan** [comment]
在 `static/assets/css/custom-style.css` 文件里把这段代码中的 `width` 值设置成你想要的值就可以了~

```css
/*左导航悬浮sidebar-menu-inner宽度调整为90px*/
.sidebar-popup.sidebar-menu-inner > div > ul > li.sidebar-item>ul{position:absolute;top:0px;left:10px;width:90px;z-index:99}
.sidebar-popup.sidebar-menu-inner ul{width:90px}
.sidebar-popup.sidebar-menu-inner ul li{width:90px}
```
